spring.application.name=petshop-doguito

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/PetShop_Doguito
spring.datasource.username=postgres
spring.datasource.password=AX-vN15!TL20Op-0-1
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
